name: chat_direct
description: A simple app to open whatsapp chats without saving numbers.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  country_flags: ^4.1.0
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.2.2
  fluttertoast: ^9.0.0
  hive_flutter: ^1.1.0
  provider: ^6.1.5+1
  url_launcher: ^6.3.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/whatsapp.svg
    - "assets/country phone codes.json"
